apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: jenkins/jnlp-slave:4.13.3-1
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: nodejs-docker
      image: node:16-alpine
      command: ['cat']  # Keep the container running for use
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      tty: true